### ISSUE TITLE
Create bash alias to run YAPI

### ISSUE THREAD

**Issue by IanDuncanT** [YetAnotherPackageInstaller/YAPI#36]
Create aliases to run yapi instead of starting sh and running yapi.sh. Alias should be yapi. An example of the alias in use would be "yapi install test".

**Comment by Wabri** [comment]
Instead of creating an alias on bash profile, we can create a softlink in the usr/local/bin directory and name it yapi. Something like this:

> sudo ln -s ~/YAPI/yapi.sh /usr/local/bin/yapi

with this you can call yapi even if you use zsh or a launcher.

**Comment by IanDuncanT** [comment]
I did not know about softlinking. This would be easier and I am going to change that to run. Does this need to run on every boot or terminal startup, similar to how alias is, or does it persist across boots?

**Comment by IanDuncanT** [comment]
I have tried this, however there is no change as python can't start from the softlink or alias.

**Comment by IanDuncanT** [comment]
I think this is fine. If you need, you can get current path with os and append the relative path. This could help running, but your solution should work. The only question I have is if subprocess is in a new terminal and would need to cd into the correct directory.

**Comment by Wabri** [comment]
If yapi.sh have this line:
https://github.com/YetAnotherPackageInstaller/YAPI/blob/ede201b7a08efce71479ba271c458ec816fa4261/yapi.sh#L1
the problem no longer exists.

**Comment by Wabri** [comment]
Yes this is not the right method to handle this problem, but for now this is the easiest way. I will open a new issue for this new problem: "set up absolute path"
