### ISSUE TITLE
Travis execution

### ISSUE THREAD

**Issue by Wabri** [YetAnotherPackageInstaller/YAPI#48]
I want travis to test the installation of all the packages. Need to create a bash script to put all the package installations and allow travis to execute them all. Like this:
```
yapi.sh install atom
yapi.sh install discord
and so on
```

**Comment by IanDuncanT** [comment]
This can be done by setting up a matrix using each package script for yapi and each python version

**Comment by IanDuncanT** [comment]
Closed in #49
