### ISSUE TITLE
Key error SCRIPT-RUNNER

### ISSUE THREAD

**Issue by IanDuncanT** [YetAnotherPackageInstaller/YAPI#82]
The config file needs to be edited to fix the section or value of script-runner and may need to be updated in code. This needs to be fixed before merging other pull requests because they feature this issue.

**Comment by Wabri** [comment]
I though the problem was thought #80  but you are right, I start to fix this problem.

**Comment by Wabri** [comment]
I try to solve this problem on PR #83 but i think the real issue is this #80
